substitutions:
  name: sp111v11
  friendly_name: SP111 V1.1
  project_name: lumascet.sp111v11
  project_version: "1.2"
  cf_pin: GPIO05
  cf1_pin: GPIO04

  current_zero: "0.14"
  # Higher value gives lower power/current readout
  current_res: "0.0010266"
  # Lower value gives lower voltage readout
  voltage_div: "1670"

dashboard_import:
  package_import_url: github://lumascet/esphome-projects/sp111v11.yaml@main
  import_full_config: false

packages:
  sp111_base: !include packages/sp111-base.yaml