substitutions:
  name: sp111v11
  friendly_name: SP111 V1.1
  project_name: lumascet.sp111v11
  project_version: "1.11"
  led_blue_pin: GPIO02
  led_red_pin: GPIO00
  relay_pin: GPIO15
  cf_pin: GPIO05
  cf1_pin: GPIO04
  flash_write_interval: 60s
  hlw_change_mode_every: "3"
  hlw_update_interval: 1s
  
  current_zero: "0.21"
  # Higher value gives lower power/current readout
  current_res: "0.0011"
  # Lower value gives lower voltage readout
  voltage_div: "1676"
  # Lower value gives lower power readout
  power_cal: "1.05"

dashboard_import:
  package_import_url: github://lumascet/esphome-projects/sp111v11.yaml@main
  import_full_config: false

packages:
  sp111_base: !include packages/sp111.yaml