substitutions:
  name: sp111v14
  friendly_name: SP111 V1.4
  project_name: lumascet.sp111v14
  project_version: "1.4"
  cf_pin: GPIO05
  cf1_pin: GPIO14

  current_zero: "0.14"
  # Higher value gives lower power/current readout
  current_res: "0.001125"
  # Lower value gives lower voltage readout
  voltage_div: "2090"

dashboard_import:
  package_import_url: github://lumascet/esphome-projects/sp111v14.yaml@main
  import_full_config: false

packages:
  sp111_base: !include packages/sp111-base.yaml