substitutions:
  name: sp1v1
  friendly_name: SP1 V1
  project_name: lumascet.sp1v1
  project_version: "1.10"
  led_blue_pin: GPIO00
  led_red_pin: GPIO02
  relay_pin: GPIO15
  cf_pin: GPIO05
  cf1_pin: GPIO14
  flash_write_interval: 60s
  hlw_change_mode_every: "3"
  hlw_update_interval: 1s

  current_zero: "0.0"
  # Higher value gives lower power/current readout
  current_res: "0.001108"
  # Lower value gives lower voltage readout
  voltage_div: "2078" 
  # Lower value gives lower power readout
  power_cal: "1.092"

dashboard_import:
  package_import_url: github://lumascet/esphome-projects/sp1v1.yaml@main
  import_full_config: false

packages:
  sp111_base: !include packages/sp1.yaml