name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2024.11.1
    with:
      #### Modify below here to match your project ####
      files: |
        sp111v11.yaml
        sp111v14.yaml
        sp112v34.yaml
        sp1v1.yaml
      esphome-version: 2024.11.3
      combined-name: energy-plugs
      #### Modify above here to match your project ####

      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2024.11.1
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}
